import {
  Box,
  Grid,
  Divider,
  Typography,
  Chip,
  IconButton,
} from "@mui/material";
import {
  Search,
  Instagram,
  Telegram,
  WhatsApp,
  GitHub,
} from "@mui/icons-material";
import { Input } from "antd";
import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import CityModal from "../components/cityModal";

import Image from "next/image";
const Home: NextPage = () => {
  const popular: string[] = [
    "تهران",
    "کرج",
    "رشت",
    "اصفهان",
    "شیراز",
    "مشهد",
    "قم",
    "تبریز",
    "اهواز",
    "یزد",
  ];

  return (
    <div>
      <Head>
        <title>بازار آنلاین</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row vh-100">
        <div className="col-md-4 order2">
          <Box className="wall">
            <p>بازار آنلاین! پایگاه خرید و فروش بی‌واسطه‌</p>
            <br />
            <p>
              اگه دنبال چیزی میگردی، شهرت رو انتخاب کن و تو دسته‌بندی‌ها به
              دنبالش بگرد.
            </p>
            <br />
            <p>
              اگر هم می‌خوای چیزی بفروشی، چند تا عکس خوب ازش بگیر و آگهیت رو
              بزار تو بازار.
            </p>
            <br />
            <Divider sx={{ borderColor: "#000" }} />
            <br />
            <Image
              src="https://s100.divarcdn.com/statics/2022/07/ecunion-logo.3ed4f870.png"
              width="80px"
              height="80px"
            />
            <Image
              src="https://s100.divarcdn.com/statics/2022/07/ecunion-logo.3ed4f870.png"
              width="80px"
              height="80px"
            />
            <Image
              src="https://s100.divarcdn.com/statics/2022/07/ecunion-logo.3ed4f870.png"
              width="80px"
              height="80px"
            />
            <br />
            <br />
            <Divider sx={{ borderColor: "#000" }} />
            <br />
            <p>ارتباط با ما</p>
            <Grid
              container
              direction="row"
              justifyContent="center"
              alignItems="center"
              spacing={2}
              sx={{ marginTop: "1.5rem" }}
            >
              <Grid container justifyContent="center" alignItems="center">
                <Grid item>
                  <IconButton>
                    <GitHub sx={{ color: "#000" }} />
                  </IconButton>
                </Grid>
                <Grid item>
                  <IconButton>
                    <Instagram sx={{ color: "#C63177" }} />
                  </IconButton>
                </Grid>
                <Grid item>
                  <IconButton>
                    <WhatsApp sx={{ color: "green" }} />
                  </IconButton>
                </Grid>
                <Grid item>
                  <IconButton>
                    <Telegram sx={{ color: "#2DA3D5" }} />
                  </IconButton>
                </Grid>
              </Grid>
            </Grid>
          </Box>
        </div>
        <div className="col-md-8 order1">
          <Box sx={{ width: "100%", marginTop: "2rem", paddingBottom: "5rem" }}>
            <Box sx={{ margin: "0 4rem" }}>
              <Input
                style={{ width: "80%" }}
                size="large"
                placeholder="جستجو در شهرها"
                className="searchInput"
                prefix={<Search sx={{ fill: "#ccc" }} />}
              />
              <Typography
                sx={{ margin: "15px 0", fontSize: "1rem", fontWeight: "400" }}
              >
                شهرهای پربازدید
              </Typography>
            </Box>
            <div className="d-flex justify-content-center align-items-center flex-wrap">
              {popular.map((city, index) => (
                <Chip
                  sx={{ width: "70px" }}
                  label={city}
                  variant="outlined"
                  key={index}
                  className="my-2 mx-3"
                  onClick={() => console.log("bye")}
                />
              ))}
            </div>
          </Box>
        </div>
      </div>
    </div>
  );
};

export default Home;
