import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState} from 'react';
import {Box,Grid,Divider} from '@mui/material';
import { Button, Modal,ConfigProvider,Input,Checkbox,Row,Col } from 'antd';
import SearchIcon from '@mui/icons-material/Search';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import CityModal from '../components/cityModal';
const Home: NextPage = () => {
  const [visible, setVisible] = useState(false);
  const [confirmLoading, setConfirmLoading] = useState(false)

  const handleOk = (): void => {
    setConfirmLoading(true);
    setTimeout(() => {
      setVisible(false);
      setConfirmLoading(false);
    }, 2000);
  };

  const showModal = ():void => {
    setVisible(true);
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>بازار آنلاین</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CityModal />
    </div>
  )
}

export default Home
